import builtins from "builtin-modules";
import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const mainOptions = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
};

// ELK (elkjs, ~1.5MB) ships as a standalone ESM file, loaded from disk on demand
// when ELK layout is enabled, so it never weighs down main.js. Bundled with no
// code-splitting so it's a single self-contained module importable via a blob URL.
const elkOptions = {
	banner: { js: banner },
	entryPoints: ["src/elk-entry.ts"],
	bundle: true,
	format: "esm",
	target: "es2018",
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	minify: prod,
	outfile: "elk.js",
};

const main = await esbuild.context(mainOptions);
const elk = await esbuild.context(elkOptions);

if (prod) {
	await main.rebuild();
	await elk.rebuild();
	process.exit(0);
} else {
	await main.watch();
	await elk.watch();
}
